from __future__ import annotations

from fastapi import APIRouter, Header, HTTPException, Query, Request
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel, Field

from api.support import (
    extract_bearer_token,
    require_admin,
    require_identity,
    resolve_image_base_url,
)
from services import gallery_service
from services.image_owners_service import get_owner


class PublishRequest(BaseModel):
    image_rel: str = Field(..., description="The rel path of image_owners in backend, e.g., 2026/05/21/abc.png")
    prompt: str = ""
    model: str = ""
    size: str = ""
    width: int = 0
    height: int = 0


class PublishedBatchRequest(BaseModel):
    image_rels: list[str] = Field(default_factory=list, description="List of rel paths to query")


def _identity_view(identity: dict) -> tuple[str, str, bool]:
    """Extract (id, display_name, is_admin) from require_identity dict."""
    role = str(identity.get("role") or "").lower()
    pid = str(identity.get("id") or "").strip()
    name = str(identity.get("name") or "").strip()
    return pid, name, role == "admin"


def create_router() -> APIRouter:
    router = APIRouter()

    @router.get("/api/gallery/feed")
    async def feed(
        request: Request,
        cursor: str | None = Query(default=None),
        limit: int = Query(default=20, ge=1, le=100),
        authorization: str | None = Header(default=None),
    ):
        """Public gallery. Accessible by any logged-in user (admin / user key).
        Returns status=visible by default; admin can specify ?include_hidden=true to view all."""
        identity = require_identity(authorization)
        pid, _, is_admin = _identity_view(identity)
        # Whether to include hidden items: only allowed if admin explicitly passes the parameter
        include_hidden = (
            is_admin
            and str(request.query_params.get("include_hidden") or "").lower() in ("1", "true", "yes")
        )
        base_url = resolve_image_base_url(request)
        return await run_in_threadpool(
            gallery_service.list_feed,
            cursor=cursor,
            limit=limit,
            image_base_url=base_url,
            include_hidden=include_hidden,
            viewer_id=pid,
        )

    @router.get("/api/gallery/items/{item_id}")
    async def item_detail(
        item_id: str,
        request: Request,
        authorization: str | None = Header(default=None),
    ):
        identity = require_identity(authorization)
        pid, _, is_admin = _identity_view(identity)
        base_url = resolve_image_base_url(request)
        item = await run_in_threadpool(
            gallery_service.get_item,
            item_id,
            base_url,
            include_hidden=is_admin,
            viewer_id=pid,
        )
        if item is None:
            raise HTTPException(status_code=404, detail={"error": "Item does not exist or has been hidden"})
        return {"item": item}

    @router.post("/api/gallery/publish")
    async def publish(
        body: PublishRequest,
        request: Request,
        authorization: str | None = Header(default=None),
    ):
        """Publish to gallery. Authorization: Any logged-in user can publish, but only their own images.
        - Validates that the owner of image_rel in image_owners equals current identity.id, otherwise 403 (prevent using others' images).
        - Matches sensitive words -> 400 (gallery_service bubbles HTTPException).
        - Duplicate publishing of the same image by the same person -> reuse the old record, idempotent.
        """
        identity = require_identity(authorization)
        pid, name, is_admin = _identity_view(identity)

        rel = body.image_rel.strip().lstrip("/")
        if not rel:
            raise HTTPException(status_code=400, detail={"error": "image_rel cannot be empty"})

        # Regular users must be the owner of the image; admin can publish any image (rare, but used for featured showcase)
        if not is_admin:
            owner = await run_in_threadpool(get_owner, rel)
            if owner != pid:
                raise HTTPException(status_code=403, detail={"error": "You can only publish images generated by yourself"})

        try:
            item = await run_in_threadpool(
                gallery_service.publish,
                image_rel=rel,
                publisher_id=pid or "admin",
                publisher_name=name or "Admin",
                prompt=body.prompt,
                model=body.model,
                size=body.size,
                width=body.width,
                height=body.height,
            )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

        # Attach the full url in the response for direct display on the frontend
        base_url = resolve_image_base_url(request)
        return {"item": gallery_service._public_view(item, base_url, viewer_id=pid)}

    @router.delete("/api/gallery/items/{item_id}")
    async def unpublish(
        item_id: str,
        authorization: str | None = Header(default=None),
    ):
        """User withdrawal / Admin deletion (hard deletion). Only author or admin."""
        identity = require_identity(authorization)
        pid, _, is_admin = _identity_view(identity)
        ok = await run_in_threadpool(
            gallery_service.unpublish, item_id, requester_id=pid, is_admin=is_admin
        )
        if not ok:
            raise HTTPException(status_code=404, detail={"error": "Item does not exist or unauthorized"})
        return {"ok": True}

    @router.post("/api/gallery/items/{item_id}/hide")
    async def admin_hide(
        item_id: str,
        authorization: str | None = Header(default=None),
    ):
        """Admin soft-hide. Unlike DELETE: does not delete the original image or discard data, only changes status to hidden,
        making it invisible in the frontend feed, but still visible to admin in the backend (include_hidden=true).
        If the author publishes the same image again, the service automatically restores it to visible."""
        require_admin(authorization)
        ok = await run_in_threadpool(gallery_service.admin_set_status, item_id, "hidden")
        if not ok:
            raise HTTPException(status_code=404, detail={"error": "Item does not exist or status unchanged"})
        return {"ok": True}

    @router.post("/api/gallery/items/{item_id}/unhide")
    async def admin_unhide(
        item_id: str,
        authorization: str | None = Header(default=None),
    ):
        """Admin restores hidden item to visible."""
        require_admin(authorization)
        ok = await run_in_threadpool(gallery_service.admin_set_status, item_id, "visible")
        if not ok:
            raise HTTPException(status_code=404, detail={"error": "Item does not exist or status unchanged"})
        return {"ok": True}

    @router.get("/api/gallery/published")
    async def my_published_lookup(
        image_rel: str = Query(..., description="The rel path of image_owners"),
        authorization: str | None = Header(default=None),
    ):
        """Check for 'My Works' page whether 'this image is published'. Returns {published: bool, item: {...}|null}.
        The frontend switches the card menu to 'Publish to Gallery' or 'Published · Withdraw' accordingly."""
        identity = require_identity(authorization)
        pid, _, _ = _identity_view(identity)
        rel = image_rel.strip().lstrip("/")
        record = await run_in_threadpool(
            gallery_service.is_published,
            image_rel=rel,
            publisher_id=pid or "admin",
        )
        if record is None:
            return {"published": False, "item": None}
        return {
            "published": record["status"] == "visible",
            "item": {
                "id": record["id"],
                "status": record["status"],
            },
        }

    @router.post("/api/gallery/published/batch")
    async def my_published_batch(
        body: PublishedBatchRequest,
        authorization: str | None = Header(default=None),
    ):
        """Batch check 'which rels are published in gallery'. Seed publishStates at once during 'My Works' page reload
        to avoid hitting the browser concurrency limit by requesting individually.
 
        Returns {[rel]: {published, id, status, publisher_name?}}, containing ONLY rels that have records.
        Unpublished rels are not present in the keys; the frontend can determine status based on key existence.
 
        Admin perspective automatically queries across users: admin in the image management page manages any user's images, only caring
        about 'whether this image has been published by anyone', regardless of the publisher. Regular users are still filtered by publisher_id.
        """
        identity = require_identity(authorization)
        pid, _, is_admin = _identity_view(identity)
        records = await run_in_threadpool(
            gallery_service.is_published_batch,
            image_rels=body.image_rels,
            publisher_id=pid or "admin",
            check_any_publisher=is_admin,
        )
        return {
            "items": {
                rel: {
                    "published": rec["status"] == "visible",
                    "id": rec["id"],
                    "status": rec["status"],
                    # Under admin view, additionally expose publisher_name for tooltip on the management page
                    # to show 'Published by xx'. It doesn't affect regular users since they already know they published it.
                    "publisher_name": rec.get("publisher_name") or "",
                }
                for rel, rec in records.items()
            }
        }

    return router
