from __future__ import annotations

from urllib.parse import quote

from fastapi import APIRouter, Header, HTTPException, Request
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel, ConfigDict

from api.support import can_use_paid_image_accounts, require_admin, require_identity, resolve_image_base_url
from services.auth_service import auth_service
from services.backup_service import BackupError, backup_service
from services.config import config
from services.image_owners_service import get_owner, owner_counts
from services.image_service import count_total_images, delete_images, download_images_zip, get_image_download_response, get_thumbnail_response, list_images
from services.image_tags_service import delete_tag, get_all_tags, set_tags
from services.log_service import log_service
from services.proxy_service import test_proxy


def _admin_owner_ids() -> set[str]:
    """Collect all admin IDs that might land in image_owners.json:
    - "admin": Fixed ID of legacy auth_key (CHATGPT2API_AUTH_KEY / config.json.auth-key)
    - Others: Admin role keys created via auth_service
    Used to distinguish "Admin Generated" from "Unowned" buckets, avoiding mixing them.
    """
    ids: set[str] = {"admin"}
    for item in auth_service.list_keys(role="admin"):
        uid = str(item.get("id") or "").strip()
        if uid:
            ids.add(uid)
    return ids


class SettingsUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="allow")


class ProxyTestRequest(BaseModel):
    url: str = ""


class ImageDeleteRequest(BaseModel):
    paths: list[str] = []
    start_date: str = ""
    end_date: str = ""
    owner: str = ""
    all_matching: bool = False

class ImageDownloadRequest(BaseModel):
    paths: list[str]

class ImageTagsRequest(BaseModel):
    path: str
    tags: list[str]

class LogDeleteRequest(BaseModel):
    ids: list[str] = []
class BackupDeleteRequest(BaseModel):
    key: str = ""


def create_router(app_version: str) -> APIRouter:
    router = APIRouter()

    @router.post("/auth/login")
    async def login(authorization: str | None = Header(default=None)):
        identity = require_identity(authorization)
        return {
            "ok": True,
            "version": app_version,
            "role": identity.get("role"),
            "subject_id": identity.get("id"),
            "name": identity.get("name"),
            "account_tier": "premium" if can_use_paid_image_accounts(identity) else "free",
            "can_use_paid_image_accounts": can_use_paid_image_accounts(identity),
            "can_use_high_resolution": can_use_paid_image_accounts(identity),
        }

    @router.get("/version")
    async def get_version():
        return {"version": app_version}

    @router.get("/api/settings")
    async def get_settings(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return {"config": config.get()}

    @router.post("/api/settings")
    async def save_settings(body: SettingsUpdateRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return {"config": config.update(body.model_dump(mode="python"))}

    @router.get("/api/images")
    async def get_images(
        request: Request,
        start_date: str = "",
        end_date: str = "",
        owner: str = "",
        authorization: str | None = Header(default=None),
    ):
        require_admin(authorization)
        return list_images(
            resolve_image_base_url(request),
            start_date=start_date.strip(),
            end_date=end_date.strip(),
            owner=owner.strip(),
            admin_ids=_admin_owner_ids(),
        )

    @router.get("/api/me/images")
    async def get_my_images(
        request: Request,
        start_date: str = "",
        end_date: str = "",
        authorization: str | None = Header(default=None),
    ):
        """My Images from the logged-in user's perspective.
 
        Uses require_identity for auth, callable by regular user keys; automatically filters
        images registered under their own ID in image_owners.json. When called by Admin, degenerates to owner=__admin__,
        returning an aggregation of all images generated by admins (semantically 'me' = the admin role).
 
        - Fetch this endpoint when Android / future clients start to merge cloud history into local Room DB.
        - The owner parameter is not exposed to prevent users from querying others' images.
        """
        identity = require_identity(authorization)
        admin_ids = _admin_owner_ids()
        role = str(identity.get("role") or "").strip()
        identity_id = str(identity.get("id") or "").strip()
        if role == "admin" or identity_id in admin_ids:
            owner_filter = "__admin__"
        else:
            owner_filter = identity_id
        return list_images(
            resolve_image_base_url(request),
            start_date=start_date.strip(),
            end_date=end_date.strip(),
            owner=owner_filter,
            admin_ids=admin_ids,
        )

    @router.get("/api/images/owners")
    async def get_image_owners(authorization: str | None = Header(default=None)):
        """Data source for user filtering dropdown in the image management page.
        Three distinct, non-overlapping categories:
        1. Regular users: List all user keys (even if count=0), since admins expect to filter by any created key.
        2. Admin (__admin__): Aggregate of images generated by all admin roles (including the legacy auth_key "admin" ID).
        3. Unowned (__unowned__): Truly orphaned images with no record in image_owners.json, mostly legacy data.
        Orphaned user IDs (user key deleted but still present in the ownership table) are listed separately, marked deleted=true.
        """
        require_admin(authorization)
        counts = owner_counts()
        admin_ids = _admin_owner_ids()
        users = auth_service.list_keys(role="user")
        items: list[dict[str, object]] = []
        seen_ids: set[str] = set()
        for user in users:
            uid = str(user.get("id") or "").strip()
            if not uid:
                continue
            seen_ids.add(uid)
            items.append({
                "id": uid,
                "name": user.get("name") or uid,
                "deleted": False,
                "count": int(counts.get(uid, 0)),
            })
        # The admin collection is already separated, so seen_ids must include admin_ids to prevent duplicates
        seen_ids |= admin_ids
        admin_count = sum(int(c) for k, c in counts.items() if k in admin_ids)
        for owner_id, count in counts.items():
            if not owner_id or owner_id in seen_ids:
                continue
            items.append({
                "id": owner_id,
                "name": owner_id,
                "deleted": True,
                "count": int(count),
            })
        items.sort(key=lambda x: (-int(x.get("count") or 0), str(x.get("name") or "")))
        # True unowned = total images - all images with an owner (including admin / active users / deleted users)
        owned_total = sum(int(v) for v in counts.values())
        unowned_count = max(0, count_total_images() - owned_total)
        # Two fixed groups; the frontend will pin them to the top of the list.
        items.append({"id": "__admin__", "name": "Admin", "deleted": False, "count": admin_count})
        items.append({"id": "__unowned__", "name": "Unowned", "deleted": False, "count": unowned_count})
        return {"items": items}

    @router.get("/image-thumbnails/{image_path:path}", include_in_schema=False)
    async def get_image_thumbnail(image_path: str):
        return get_thumbnail_response(image_path)

    @router.post("/api/images/delete")
    async def delete_images_endpoint(body: ImageDeleteRequest, authorization: str | None = Header(default=None)):
        """Image deletion:
          - admin: Full control, can delete by path, owner, or all_matching filter.
          - user: Can only delete their own images by path (owner == identity.id in image_owners.json).
            Other filtering parameters (start_date / end_date / owner / all_matching) are ignored
            to prevent accidentally treating all_matching=true as a 'clear all' operation.
        """
        identity = require_identity(authorization)
        role = str(identity.get("role") or "").lower()
        if role == "admin":
            return delete_images(
                body.paths,
                start_date=body.start_date.strip(),
                end_date=body.end_date.strip(),
                owner=body.owner.strip(),
                all_matching=body.all_matching,
                admin_ids=_admin_owner_ids(),
            )
        # Standard user path: only allow deletion of owned images by paths
        user_id = str(identity.get("id") or "").strip()
        if not user_id:
            raise HTTPException(status_code=403, detail={"error": "Unauthorized deletion"})
        requested = [p.strip().lstrip("/") for p in (body.paths or []) if p and p.strip()]
        # Owner validation: every path must have owner == self; discard otherwise
        # This way, if the client sends other people's images by mistake, they just aren't deleted, avoiding ownership leaks
        owned = [rel for rel in requested if get_owner(rel) == user_id]
        if not owned:
            return {"removed": 0}
        return delete_images(owned)

    @router.post("/api/images/download")
    async def download_images_endpoint(body: ImageDownloadRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        buf = download_images_zip(body.paths)
        return StreamingResponse(
            buf,
            media_type="application/zip",
            headers={"Content-Disposition": 'attachment; filename="images.zip"'},
        )

    @router.get("/api/images/download/{image_path:path}")
    async def download_single_image_endpoint(image_path: str, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return get_image_download_response(image_path)

    @router.get("/api/logs")
    async def get_logs(type: str = "", start_date: str = "", end_date: str = "", authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return {"items": log_service.list(type=type.strip(), start_date=start_date.strip(), end_date=end_date.strip())}

    @router.post("/api/logs/delete")
    async def delete_logs(body: LogDeleteRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return log_service.delete(body.ids)

    @router.post("/api/proxy/test")
    async def test_proxy_endpoint(body: ProxyTestRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        candidate = (body.url or "").strip() or config.get_proxy_settings()
        if not candidate:
            raise HTTPException(status_code=400, detail={"error": "proxy url is required"})
        return {"result": await run_in_threadpool(test_proxy, candidate)}

    @router.get("/api/storage/info")
    async def get_storage_info(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        storage = config.get_storage_backend()
        return {
            "backend": storage.get_backend_info(),
            "health": storage.health_check(),
        }

    @router.post("/api/backup/test")
    async def test_backup_connection(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            return {"result": await run_in_threadpool(backup_service.test_connection)}
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

    @router.get("/api/backups")
    async def get_backups(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            return {
                "items": await run_in_threadpool(backup_service.list_backups),
                "state": backup_service.get_status(),
                "settings": backup_service.get_settings(),
            }
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

    @router.post("/api/backups/run")
    async def run_backup_endpoint(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            return {"result": await run_in_threadpool(backup_service.run_backup)}
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

    @router.post("/api/backups/delete")
    async def delete_backup_endpoint(body: BackupDeleteRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            await run_in_threadpool(backup_service.delete_backup, body.key)
            return {"ok": True}
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

    @router.get("/api/backups/detail")
    async def get_backup_detail(key: str = "", authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            return {"item": await run_in_threadpool(backup_service.get_backup_detail, key)}
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc

    @router.get("/api/backups/download")
    async def download_backup_endpoint(key: str = "", authorization: str | None = Header(default=None)):
        require_admin(authorization)
        try:
            item = await run_in_threadpool(backup_service.download_backup, key)
        except BackupError as exc:
            raise HTTPException(status_code=400, detail={"error": str(exc)}) from exc
        filename = str(item.get("name") or "backup.bin")
        quoted = quote(filename)
        headers = {
            "Content-Disposition": f"attachment; filename*=UTF-8''{quoted}",
            "Content-Length": str(int(item.get("size") or 0)),
        }
        return Response(
            content=bytes(item.get("payload") or b""),
            media_type=str(item.get("content_type") or "application/octet-stream"),
            headers=headers,
        )


    @router.get("/api/images/tags")
    async def list_image_tags(authorization: str | None = Header(default=None)):
        require_admin(authorization)
        return {"tags": get_all_tags()}

    @router.post("/api/images/tags")
    async def update_image_tags(body: ImageTagsRequest, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        rel = body.path.strip().lstrip("/")
        if not rel:
            raise HTTPException(status_code=400, detail={"error": "path is required"})
        tags = set_tags(rel, body.tags)
        return {"ok": True, "tags": tags}

    @router.delete("/api/images/tags/{tag}")
    async def delete_image_tag(tag: str, authorization: str | None = Header(default=None)):
        require_admin(authorization)
        count = delete_tag(tag)
        return {"ok": True, "removed_from": count}

    return router
